### PR TITLE
Switch to NextPNR

### PR DESCRIPTION
**Pull request by felipebalbi**
Signed-off-by: Felipe Balbi <felipe@balbi.sh>

### CODE REVIEW

**Comment by TsvetanUsunov** [comment]
we try to compile but:

Package nextpnr-ice40 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by felipebalbi** [comment]
which distribution are you using? I'm using Archlinux, but the package exists on ubuntu too: https://packages.ubuntu.com/search?keywords=nextpnr&searchon=names&suite=all&section=all

**Comment by TsvetanUsunov** [comment]
we try to stick only to LTS and use ubuntu 20.04 LTS

**Comment by felipebalbi** [comment]
alright, let's skip this pr, then

**Pull request closed without merging**
